workspace(name = "sonar_audio_verifier")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Rules Python for Python support
http_archive(
    name = "rules_python",
    sha256 = "9d04041ac92a0985e344235f5d946f71ac543f1b1565f2cdbc9a2aaee8adf55b",
    strip_prefix = "rules_python-0.26.0",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.26.0/rules_python-0.26.0.tar.gz",
)

load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_toolchains")

py_repositories()

# Register Python 3.14 toolchain
python_register_toolchains(
    name = "python3_14",
    python_version = "3.14",
)

# Rules Nixpkgs for Nix integration (optional)
http_archive(
    name = "io_tweag_rules_nixpkgs",
    sha256 = "b1c69d72f36e6e5b1e5e7c4e0e7c4e0e7c4e0e7c4e0e7c4e0e7c4e0e7c4e0e7",
    strip_prefix = "rules_nixpkgs-0.10.1",
    urls = ["https://github.com/tweag/rules_nixpkgs/archive/v0.10.1.tar.gz"],
)

load("@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl", "nixpkgs_git_repository", "nixpkgs_package")

# Nixpkgs repository
nixpkgs_git_repository(
    name = "nixpkgs",
    revision = "nixos-24.05",  # Pin to a stable NixOS version
)

